env:
  matrix:
  - TRAVIS_PYTHON_VERSION="2.6" NUMPY_VERSION="1.9"
  - TRAVIS_PYTHON_VERSION="2.7" NUMPY_VERSION="1.9"
  - TRAVIS_PYTHON_VERSION="2.7" NUMPY_VERSION="1.10"
  - TRAVIS_PYTHON_VERSION="3.3" NUMPY_VERSION="1.9"
  - TRAVIS_PYTHON_VERSION="3.4" NUMPY_VERSION="1.9"
  - TRAVIS_PYTHON_VERSION="3.4" NUMPY_VERSION="1.10"
  global:
    secure: UxPkdFKl0xtk+H+98CNHSnYN8SJrEq5xJjLtPUPR+5UF5lLKL7godwrOdYeO0B0fXPi2Plw0vtoIID6H1AV4x+8QD/AgAizoWIh8KLim3E7rDX0v0M3WnUHctvYwt76mGCYvIGH6qR2Ziml37Ec6nz2aTuz0oex27P6dq0BKkXs=
os:
- linux
- osx
matrix:
  allow_failures:
  - os: osx
    env: TRAVIS_PYTHON_VERSION="2.6" NUMPY_VERSION="1.9"
sudo: false
install:
- echo "Build on $TRAVIS_OS_NAME for Python $TRAVIS_PYTHON_VERSION"
- bash .ci/travis/install_python.sh
- export PATH="$HOME/miniconda/bin:$PATH"
- source activate test-env
- pip install coveralls
- conda install numpy=$NUMPY_VERSION
- conda install scipy
- python setup.py install
script:
- if [[ "$TRAVIS_PYTHON_VERSION" == 2.7 ]]; then (cd docs && make html 2> /dev/null); fi
- bash .ci/travis/run_travis_test.sh
virtualenv:
  system_site_packages: false
after_success:
  - bash .ci/travis/deploy_to_pypi.sh
  - coveralls
deploy:
  provider: pypi
  user: mcflugen
  password:
    secure: V15DceMv4DUmjgxToaxrP3KaQxsLbfrTkB1s6D8YNQZvYJiVvNlBpC1nF8yWbOt3IWJQSGjaQEnObd2ZhHe2Kq/H+QsEFyBKlYF7SNp35FyS5zLuf2qhnNhmzhqkspwBpiGe88c1PQPFzfqdIUQXp7ZAv6L8YRvNy2sbzvgxh6I=
  on:
    tags: true
    branch: release
    repo: landlab/landlab
  distributions: sdist bdist_wheel
notifications:
  slack:
    secure: gRKbqjPgp0ZcFtecHOwjLAFbzzBr2zyFrxk7OAS/cea/9U8bLQNA0jZs3ZHtAgR53gdnFlx/GI10d/KD9XMKU55gQkO4FSvfYMK7Xzs2tfnEa5flTqQKRfjB1oJ2fmb81yshUe+xKsXBoedP7SPYv2mutMOY8srKwUcuE0yGmAw=
