environment:

  global:
    PYTHON: "C:\\conda"
    MINICONDA_VERSION: "3.5.5"
    WITH_COMPILER: "cmd /E:ON /V:ON /C .\\.ci\\appveyor\\run_with_env.cmd"
    NUMPY_VERSION: "1.9.1"
    PYPI_PASS:
      secure: 8om/mA+rp/SBcVXDrFC9LgyKPcEmlseSUT4WBBOgfYM=

  matrix:
    - PYTHON: "C:\\Miniconda"
      DISTUTILS_USE_SDK: "1"
      PYTHON_VERSION: "2.6"
    - PYTHON: "C:\\Miniconda"
      DISTUTILS_USE_SDK: "1"
      PYTHON_VERSION: "2.7"
    - PYTHON: "C:\\Miniconda3"
      DISTUTILS_USE_SDK: "1"
      PYTHON_VERSION: "3.3"
    - PYTHON: "C:\\Miniconda3"
      DISTUTILS_USE_SDK: "1"
      PYTHON_VERSION: "3.4"
    - PYTHON: "C:\\Miniconda3"
      PYTHON_VERSION: "3.5"
      NUMPY_VERSION: "1.10"

platform:
  - x64
  - x86

init:
  - "ECHO %PYTHON% %PYTHON_VERSION% %PLATFORM%"
  - "ECHO %APPVEYOR_REPO_BRANCH%"

install:
  - IF "%PLATFORM%"=="x64" (SET SUFFIX="-x64") ELSE (SET SUFFIX="")
  - "SET PATH=%PYTHON%%SUFFIX%;%PYTHON%%SUFFIX%\\Scripts;%PATH%"
  - ECHO "Using %PYTHON%%SUFFIX%"
  - "conda create -q --yes -n test python=%PYTHON_VERSION%"
  - "activate test"
  - "python --version"
  - "conda install -q --yes numpy=%NUMPY_VERSION% pip jinja2 scipy nose>=1.3 matplotlib netCDF4 sympy pandas Cython pyyaml"
  - "pip install wheel"
  - "pip install twine"
  - "%WITH_COMPILER% python setup.py install"

build: false

test_script:
  #- "%WITH_COMPILER% python setup.py build_ext --inplace"
  #- "%WITH_COMPILER% python coupled_driver.py"
  - "%WITH_COMPILER% python scripts/test-installed-landlab.py"

after_test:
  - "%WITH_COMPILER% python setup.py bdist_wheel"

artifacts:
  # Archive the generated conda package in the ci.appveyor.com build report.
  - path: 'dist\*'

deploy_script:
  - "powershell .ci/appveyor/deploy_to_pypi.ps1"

notifications:
  - provider: Slack
    auth_token:
      secure: hvij8zEmE9LqjvwUJteiIZdwutlETmcJWwI/PtQEiAn3Hb2J+SH0Ye+pxMot2J2mc4i+zeNpHlzu8NV2CcLXzA==
    channel: "#testing"
